kind: Service
apiVersion: v1
metadata:
  name: shopping-app-service
  namespace: flux-shopping-app
spec:
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort
