#namespace: shoppingapp

image:
  repository: madhurasr/shoppingdemo
  tag: "v2"
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: NodePort
  port: 5173
  targetPort: 5173
 # nodePort: 31573   # You can remove this if you want Kubernetes to assign automatically

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 35
