apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapp
  labels:
    app: shoppingapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shoppingapp
  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
        - name: shoppingapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5173
