apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shoppingapp
  labels:
    app: shoppingapp
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: shoppingapp

  template:
    metadata:
      labels:
        app: shoppingapp
    spec:
      containers:
        - name: shoppingapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5173

  strategy:
    canary:
      canaryService: shoppingapp-canary
      stableService: shoppingapp-stable

      trafficRouting:
        nginx:
          stableIngress: shoppingapp-ingress

      steps:
        - setWeight: 20
        - pause: { duration: 10 }
        - setWeight: 50
        - pause: { duration: 20 }
