apiVersion: v1
kind: Service
metadata:
  name: shoppingapp-stable
spec:
  selector:
    app: shoppingapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
