apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoppingapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: shoppingapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shoppingapp-stable
            port:
              number: {{ .Values.service.port }}
